export interface ITheme {
  SHORTEN_BTN_BACKGROUND: string;
  SHORTEN_BTN_LABEL: string;
  SIGNUP_BTN_BACKGROUND: string;
  SIGNUP_BTN_LABEL: string;
  LOGIN_BTN_BACKGROUND: string;
  LOGIN_BTN_LABEL: string;
  HEADER: string;
  LOGO_BACKGROUND: string;
  LOGO_ICON: string;
  BRAND: string;
  SHORT_LINK: string;
  COPY_BTN_BACKGROUND: string;
  COPY_BTN_ICON: string;
  VIEWS_BTN_BACKGROUND: string;
  VIEWS_BTN_LABEL: string;
  MODAL_SIGNUP_BACKGROUND: string;
  MODAL_SIGNUP_TEXT: string;
  MODAL_SIGNUP_BTN_BACKGROUND: string;
  MODAL_SIGNUP_BTN_LABEL: string;
  MODAL_LOGIN_BACKGROUND: string;
  MODAL_LOGIN_TEXT: string;
  MODAL_LOGIN_BTN_BACKGROUND: string;
  MODAL_LOGIN_BTN_LABEL: string;
  BODY_BACKGROUND: string;
  CARD_BACKGROUND: string;
  USER_EMAIL: string;
}